POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento 2",
  "details": null,
  "maximumAttendees": 1
}
###

POST http://localhost:3333/events/aaa2475b-5d92-4b03-ab24-85b80f3458a7/attendees
Content-Type: application/json

{
  "name": "Marcos Gomes",
  "email": "marcosgomesdev@gmail.com"
}

###

GET http://localhost:3333/events/aaa2475b-5d92-4b03-ab24-85b80f3458a7

###
GET http://localhost:3333/attendees/8/badge